apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: resources-burner
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-97-tenant/load-app-83968ff6-dce2-423e-babf-76742daa73c4/resources-burner@sha256:4fb3ea4f7f04f3ae6e19d5b4e16ec82bc33813dfe20b7c6cdcef8e7c00f40d51
        name: container-image
        resources: {}
status: {}
